[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "broccoli creek celery casino warfare blast pilot casual material inquiry pattern sad correct later success alpha sister off minute face salute either proof announce"
